/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post126, git sha1 b5170e139) */

(* top =  1  *)
(* src = "C:\\ever\\chipdesign\\chip.py:13" *)
(* generator = "Amaranth" *)
module top(vector_b, start, clk, rst, accum, vector_a);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire [15:0] \$1 ;
  wire [16:0] \$2 ;
  reg [15:0] \$3 ;
  (* src = "C:\\ever\\chipdesign\\chip.py:9" *)
  output [15:0] accum;
  reg [15:0] accum = 16'h0000;
  (* src = "C:\\Users\\everl\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\everl\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "C:\\ever\\chipdesign\\chip.py:10" *)
  input start;
  wire start;
  (* src = "C:\\ever\\chipdesign\\chip.py:7" *)
  input [7:0] vector_a;
  wire [7:0] vector_a;
  (* src = "C:\\ever\\chipdesign\\chip.py:8" *)
  input [7:0] vector_b;
  wire [7:0] vector_b;
  assign \$1  = vector_a * (* src = "C:\\ever\\chipdesign\\chip.py:18" *) vector_b;
  assign \$2  = accum + (* src = "C:\\ever\\chipdesign\\chip.py:18" *) \$1 ;
  (* src = "C:\\ever\\chipdesign\\chip.py:9" *)
  always @(posedge clk)
    accum <= \$3 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$3  = accum;
    if (start) begin
      \$3  = \$2 [15:0];
    end
    if (rst) begin
      \$3  = 16'h0000;
    end
  end
endmodule
